---
name: EN
channels: [huggingface, pytorch, conda-forge, nodefaults]
dependencies:
  - conda-lock
  - ipykernel
  - jupyterlab
  - pdbpp
  - pip >=21.1
  - plotly>=5.13.0
  - pre-commit
  - pytask-latex
  - pytask-parallel
  - pytask>=0.2
  - python-graphviz
  - python=3.11
  - pyyaml
  - setuptools_scm
  - statsmodels
  - toml

  # data
  - kaggle
  # basics
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn

  # sklearn
  - scikit-learn
  - scikit-image

  # huggingface
  - transformers
  - tokenizers
  - datasets
  - sentencepiece
  - tensorboardX  # Add tensorboardX as a dependency
  - pip:
      - torch
      - torchvision
      - torchtext
      - huggingface_hub[cli]
      - -e .
      - kaleido
      - transformers[torch]  # needed?
      - accelerate -U  # needed?
      - accelerate>=0.20.1  # needed?
